version: '3.8'

services:
  app:
    build: .
    ports:
      - '4000:4000'
    environment:
      DB_HOST: db
      DB_NAME: mydatabase
      DB_USER: user
      DB_PASS: Ganesh6301
      JWT_SECRET: mysecretkey
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: Ganesh6301
    ports:
      - '5432:5432'
